runtime: go111

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
  - url: /static
    static_dir: static
    secure: always
  - url: /sig
    static_dir: sig
    secure: always
    http_headers:
      Access-Control-Allow-Origin: '*'
  - url: /.*
    script: auto
